### ISSUE TITLE
Still SDL ERROR 

### ISSUE THREAD

**Issue by Gustsonic1682** [MAJigsaw77/Funkin#10]
I SEE that you close my bug report and updated APK but the bug still happend

**Comment by moondroidcoder** [comment]
Hey sorry to close this abruptly but we're fixing on the upcoming patch! The update is not out :) Please be patient

**Comment by Gustsonic1682** [comment]
Thanks you im gonna be patient :) (Zack you finally back, i remember to be downloading your optimization of Friday night vibing
