### ISSUE TITLE
Bug Report: certain (every) mods cutscenes didn't work properly 

### ISSUE THREAD

**Issue by sarvstuff** [MAJigsaw77/Funkin#14]
not like the weekend cutscene, every mods i installed that have a video/cutscene didn't work properly

silly billy, tricky, etc (idk if its the port bug or the mod bc i seek the mods flies)

**Comment by moondroidcoder** [comment]
how exactly does it not work? Is there an error log or does it only show a blackscreen

**Comment by aguylol34** [comment]
> how exactly does it not work? Is there an error log or does it only show a blackscreen

something like this:Polymod Script Import Error
Import error in hscriptClass(assets/scripts/songs/
silly-billy/silly.hxc)
Could not import unknown class
hxcodec.flixel.FlxVideoSprite
Check to ensure the class exists and is spelled
correctly.

**Comment by moondroidcoder** [comment]
Ah, you might need to edit these scripts yourself
just change it accordingly from hxcodec to hxvlc
