### ISSUE TITLE
Bug Report: [Can't run the game after downloading 0.4.1 - Unsupported]

### ISSUE THREAD

**Issue by Mint-y** [MAJigsaw77/Funkin#16]
Hi, sorry for bothering y'all, but I got something to report. Title basically says it all, can't get the game to run after updating to 0.4.1. Trying to reinstall gives a message saying the app was built for an older version of Android, and ignoring it works, but I can't open the APK at all afterwards.

Device: Samsung Galaxy S20FE 5G.
OS: Android 13 (API 33).

![20240621_191220.jpg](https://github.com/FunkinDroidTeam/Funkin/assets/111752984/db21a71a-bb6a-4361-83a6-2f8e1eff0160)

![Screenshot_20240621_195359_Google Play Store.jpg](https://github.com/FunkinDroidTeam/Funkin/assets/111752984/595fb7d5-67f5-45ef-83ad-450f36306f9e)

**Comment by moondroidcoder** [comment]
Aw man, we feared this would happen. Have you tried clicking on more details and see if you can allow the app somehow?

**Comment by Klaskycs** [comment]
I Don't Know How To Play
![Screenshot_٢٠٢٤٠٦٢٢_٠٢٣٥٣١](https://github.com/FunkinDroidTeam/Funkin/assets/161109546/5b932492-fc29-4d7b-94b9-283e9e725029)
![Screenshot_٢٠٢٤٠٦٢٢_٠٢٣٥١٨](https://github.com/FunkinDroidTeam/Funkin/assets/161109546/f5257684-d614-42fb-ad04-cde80f56d313)

**Comment by ghost** [comment]
@Mint-y I don't get it by what you say, after ignoring the play protect thing, does fnf starts?

**Comment by moondroidcoder** [comment]
@Klaskycs please open a seperate issue and explain it properly instead of showing a screenshot of your comment

**Comment by Klaskycs** [comment]
How?

**Comment by Klaskycs** [comment]
And How To Play Fnf On My Phone Is Not On The List

**Comment by Mint-y** [comment]
> @Mint-y I don't get it what you say, after ignoring the play protect thing, does fnf starts

Nope, it doesn't. 
I can download the game, but it doesn't show up on my home screen, and even after giving all permissions I could through the OS settings - I still couldn't get it to start.
It's definitely here... Somewhere...? But I just can't do anything about it, at all. 
Really, REALLY weird.

**Comment by Klaskycs** [comment]
Why

**Comment by moondroidcoder** [comment]
> > @Mint-y I don't get it what you say, after ignoring the play protect thing, does fnf starts
> 
> Nope, it doesn't. I can download the game, but it doesn't show up on my home screen, and even after giving all permissions I could through the OS settings - I still couldn't get it to start. It's definitely here... Somewhere...? But I just can't do anything about it, at all. Really, REALLY weird.

We're currently narrowing this down internally, there's an unused feature that made it into the game which uses experimental storage stuff to import zip mods into the game. It could be because of that, just stay with us we might be able to send a build to remedy this soon

**Comment by Vini158916** [comment]
I'm literally having this same problem, and the coincidence is, I have a Samsung S20 FE 5g

**Comment by Klaskycs** [comment]
How To Fix This Bug On Fnf Android 0.4.1 Now

**Comment by Klaskycs** [comment]
Why You Delete My Comnent

**Comment by Mint-y** [comment]
> > > @Mint-y I don't get it what you say, after ignoring the play protect thing, does fnf starts
> > 
> > Nope, it doesn't. I can download the game, but it doesn't show up on my home screen, and even after giving all permissions I could through the OS settings - I still couldn't get it to start. It's definitely here... Somewhere...? But I just can't do anything about it, at all. Really, REALLY weird.
> 
> We're currently narrowing this down internally, there's an unused feature that made it into the game which uses experimental storage stuff to import zip mods into the game. It could be because of that, just stay with us we might be able to send a build to remedy this soon

Understood, take as long as y'all need! Thank you so much for the support and I'm really sorry for explaining the issue so badly. 
Have a nice day.

**Comment by moondroidcoder** [comment]
@Mint-y Can you test this out?
https://github.com/FunkinDroidTeam/Funkin/actions/runs/9621435211/artifacts/1626796826

**Comment by moondroidcoder** [comment]
Fixed on v0.4.1-patch-1!
