### ISSUE TITLE
Bug Report: How To Play Fnf 0.4.1 On Android

### ISSUE THREAD

**Issue by Klaskycs** [MAJigsaw77/Funkin#18]
HOW TO PLAY FNF 0.4.1 ON ANDROID 
I CAN'T PLAY FNF 0.4.1 ON MY PHONE BECAUSE OF REMOVING OPEN BUTTON

**Comment by moondroidcoder** [comment]
Can you please talk normally we geneuinely do not understand you

**Comment by Vini158916** [comment]
The apk is bugged, everyone is having this problem, but I think they will fix that soon

**Comment by ghost** [comment]
*sigh* duplicate of #16
