### ISSUE TITLE
Bug Report: Performance issue (32 bit)

### ISSUE THREAD

**Issue by Newoplo** [MAJigsaw77/Funkin#22]
just performance issue just the game need even more optimized because in the free play i get 6 fps (the latest version)

**Comment by moondroidcoder** [comment]
What are your device's specifications

**Comment by Newoplo** [comment]
> What are your device's specifications

can you make it for 1gb and 2gb my phone is 3gb 32 bit samsung galaxy a02

**Comment by ghost** [comment]
your cpu is [MediaTek MT6739WW](https://www.notebookcheck.net/Mediatek-MT6739WW-SoC-Benchmarks-and-Specs.420676.0.html) expect performance issues.

**Comment by moondroidcoder** [comment]
We will try optimizing the game without diminishing the quality of the code/game but dont keep your hopes up. As of now this wont get a fix
