### ISSUE TITLE
BLAZIN' SONG CRASHES THE GAME

### ISSUE THREAD

**Issue by DHyperYT** [MAJigsaw77/Funkin#23]
## Describe the bug
The game crashes as soon as it starts loading the song Blazin'. Also note that if you go in Story Mode and look at Weekend 1's songs Blazin' is missing

## To Reproduce
Play through Weekend 1 on Hard mode and it crashes with the error in the screenshot as soon as the 2nd cutscene finishes (after 2hot and before Blazin')
![Screenshot_2024-06-29-19-47-56-46_84ebc69715f4fb726850135bf96ff0e9.jpg](https://github.com/FunkinDroidTeam/Funkin/assets/79223072/286fea8c-7130-42ca-a147-6b3d105a6884)

PLATFORM: ANDROID
VERSION: v0.4.1 (patch 1)

**Comment by moondroidcoder** [comment]
This is honestly confusing. 
@KarimAkra I think you talked about this before?

**Comment by KarimAkra** [comment]
Blazin' is a secret song that's why it dosen't show in story mode

as for the crash we're trying to figure it out

**Comment by DHyperYT** [comment]
> Blazin' is a secret song that's why it dosen't show in story mode
> 
> as for the crash we're trying to figure it out

I don't know if this helps but i found that as a workaround to this crash you can simply go in the song's metadata and change volume3 to something else (i changed it to volume2) and it works fine
![Screenshot_2024-06-29-21-36-57-37_84ebc69715f4fb726850135bf96ff0e9.jpg](https://github.com/FunkinDroidTeam/Funkin/assets/79223072/5fa41548-a2e4-4305-8257-39365563f0b7)

**Comment by moondroidcoder** [comment]
Are you sure this isnt simply just a one-off accident the game did?

**Comment by DHyperYT** [comment]
> Are you sure this isnt simply just a one-off accident the game did?

Yeah you're right actually, i got the unmodified release from this repo again and it works now

**Comment by DHyperYT** [comment]
Started happening again ![Screenshot_2024-06-30-11-10-52-89_84ebc69715f4fb726850135bf96ff0e9.jpg](https://github.com/FunkinDroidTeam/Funkin/assets/79223072/dd62dd94-017f-4b91-86a9-b69ba27e4cc7)

**Comment by moondroidcoder** [comment]
yeah this is either a mod or just happening due to lower framerate. Closing as not planned but would keep in mind
