### ISSUE TITLE
Bug Report: Weekend one cannot be completed 

### ISSUE THREAD

**Issue by Crappy-Productions** [MAJigsaw77/Funkin#25]
## Describe the bug
Weekend one cannot be completed due to the game crashing when trying to load into Blazin' (only tested in normal mode)
## To Reproduce
1: use the lastest android build from action
2: play the Weekend 1 in normal mode
3: game crashes with a null object reference after the 2Hot cutscene (skipping it will result the same)
## Expected behavior
game will experience a fatal crash

## Screenshots/Video
![Screenshot_2024-07-07-09-17-36-314_com funkin fnf](https://github.com/FunkinDroidTeam/Funkin/assets/98716926/88229d0a-9100-4143-ae48-ccd4a2509931)

## Desktop
 - OS:
android 
 - Version:
0.4.1 (action Build Game for Android#134)

**Comment by moondroidcoder** [comment]
I wonder why this is happening so universally and at random, perhaps of mods?
