### ISSUE TITLE
Compiling Error: .gradle wrapper (The system cannot find the specified path)

### ISSUE THREAD

**Issue by LexiLikesFunkin** [MAJigsaw77/Funkin#26]
I'm not sure if this is a bug, or something that didn't install correctly, but here goes
Edit: the markdown didn't work, it looks like this for a variety of bits 

![image](https://github.com/FunkinDroidTeam/Funkin/assets/154026059/0f6d0318-a472-486a-b710-2d2fa9d3b5ce)

From Joel On Software:

"It’s pretty easy to remember the rule for a good bug report. Every good bug report needs exactly three things.

1. Steps to reproduce: I just tried to compile, I followed the guide and everything (Except NDK didn't install correctly, so I did that manually, and assigned the path, would've got a different error if it wasn't right)

2. What you expected to see: A folder with the compiled game

3. What you saw instead: A hell of a bunch of errors

-->

## Describe the bug
Refer to the top of the page, the errors happen a long way into compiling, and don't resolve on their own / produce a finished build

## To Reproduce
I wish I could say how to reproduce it
## Expected behavior
I wanted the game to finish compiling as normal

## Desktop
 - OS:
 Windows 11 Home - x64
 - Browser
Not sure how this helps, but OperaGX
 - Version:
I tried 0.2.7.1 (the old version) and 0.4.1(?)

**Comment by ghost** [comment]
please use our hxcpp (https://github.com/FunkinDroidTeam/hxcpp)

**Comment by LexiLikesFunkin** [comment]
Ohhh
I'll try and give another update

**Comment by LexiLikesFunkin** [comment]
Oh, will this stop me from being able to compile to Windows?

**Comment by ghost** [comment]
nope

**Comment by LexiLikesFunkin** [comment]
Awesome, thank you!

**Comment by LexiLikesFunkin** [comment]
ERROR: JAVA_HOME is set to an invalid directory: C:\Users\[USER]\AppData\Local\Android\Sdk\jdk\jdk-17.0.11+9

**Comment by ghost** [comment]
make sure jdk path is correct

**Comment by LexiLikesFunkin** [comment]
It's correct
I think the batch file set it automatically, but it's correct

**Comment by LexiLikesFunkin** [comment]
I'd be happy to resolve this on Discord if you have any other suggestions, my @ is just lexilikesfunkin
Thanks!

**Comment by moondroidcoder** [comment]
Check if that directory exists! Could be a mishap from the batch file itself, and if it does exist make sure the folder isnt empty

**Comment by LexiLikesFunkin** [comment]
okay, no, yeah, the bat file gave it the wrong location
haxelib run lime config JAVA_HOME %LOCALAPPDATA%\Android\Sdk\jdk\jdk-17.0.11+9
![image](https://github.com/FunkinDroidTeam/Funkin/assets/154026059/61ef29de-af8d-4776-a370-0b78481ea389)

**Comment by LexiLikesFunkin** [comment]
![image](https://github.com/FunkinDroidTeam/Funkin/assets/154026059/f7afc398-e405-4666-afae-5c78e9b63422)
nvm still not wanting to work

**Comment by ghost** [comment]
can u delete .gradle from user root dir and try recompile

**Comment by LexiLikesFunkin** [comment]
may i get the path?
edit: i mean because searching gradle took too long, and didnt give results
edit 2: okay i might be stupid, but it still netted no results
![image](https://github.com/FunkinDroidTeam/Funkin/assets/154026059/3ec1b76f-4419-4931-88a7-6dfba061b0b1)
_There is no gradle._

**Comment by moondroidcoder** [comment]
![image](https://github.com/FunkinDroidTeam/Funkin/assets/81515012/155c8960-a534-4b5e-a966-5f455dbc3764)
I think she meant this

**Comment by LexiLikesFunkin** [comment]
There isn't a .gradle directory '(The system cannot find the path specified)'

**Comment by moondroidcoder** [comment]
Just to make sure, try doing "lime setup android" and enter 3 times
then send a screenshot

**Comment by LexiLikesFunkin** [comment]
![image](https://github.com/FunkinDroidTeam/Funkin/assets/154026059/e2ca5553-336e-430c-8280-8c048fb03ee7)

**Comment by ghost** [comment]
can u try removing export folder and recompiling then?

**Comment by moondroidcoder** [comment]
Try deleting the android folder in the export folder, and try again.
If it doesnt work it *could* be because of admin perms.

**Comment by LexiLikesFunkin** [comment]
Okay, recompiling now, this'll have to be the last thing I try, it's late and I need to get to bed. If it doesn't work I'll make another comment tomorrow when I’m on my pc

**Comment by moondroidcoder** [comment]
Sorry for the inconvenience! This is a new case for us despite working on this for years

**Comment by LexiLikesFunkin** [comment]
That's okay!! And I’m sorry that this has been such a hassle!
It's still compiling, and it looks promising, though it got pretty far last time before failing...

**Comment by LexiLikesFunkin** [comment]
No... it went back to the .gradle issue
I’m sorry that this has taken so long as well, I was hoping it would be a one and done type scenario, but I guess it'll have to be carried over to tomorrow
I'll leave the issue open, so I can quickly come back to it when I’m up

**Comment by ghost** [comment]
just to make sure have u run hmm on funkin repo? (haxelib run hmm install) cuz u have to cuz we use some our libraries for mobile support

**Comment by LexiLikesFunkin** [comment]
I think I have, though I'm off my pc now so I'll have to check tomorrow
I feel like that's what the problem will be not gonna lie, if it is I am very sorry for that

**Comment by ghost** [comment]
that's fine dw we all make mistakes

**Comment by LexiLikesFunkin** [comment]
I got this after compiling
Funkin' Android/.haxelib/polymod/git/polymod/backends/LimeBackend.hx:146: characters 54-55 : Unexpected ?
![image](https://github.com/FunkinDroidTeam/Funkin/assets/154026059/07a07786-1737-4341-8f89-19cdbe83b83e)

**Comment by moondroidcoder** [comment]
Update your haxe to the latest version

**Comment by LexiLikesFunkin** [comment]
I'm gonna do a fresh install of source as well...
I tried doing it in a project i'm working on solo, and i got a .gradle error again, as there isn't a gradle directory in my users folder
Edit: I think it's worth saying that it's basically a fresh copy of HelloWorld right now, there isn't anything special in the code yet, it's just assets

**Comment by LexiLikesFunkin** [comment]
After 10 painful minutes of compiling, it failed again with another .gradle error, '(The system cannot find the path specified)'
![image](https://github.com/FunkinDroidTeam/Funkin/assets/154026059/2a396a22-1474-4a98-9422-6ac04de0f41d)

**Comment by moondroidcoder** [comment]
maybe try opening the terminal tab with admin permissions? (Run as administrator)

**Comment by LexiLikesFunkin** [comment]
I searched all over my user profile, there isn't a .gradle folder, is there a library i have to install? i did run the hmm file and everything

**Comment by moondroidcoder** [comment]
The thing here is that it couldnt the path itself it might need elevated permissions.

**Comment by LexiLikesFunkin** [comment]
Oh, I see,,,
Even with elevated permissions, it wouldn't be able to move the files to the user profile, the same thing happened yesterday with the NDK move with elevated perms
I might have to move it manually

I couldn't get it working [edit]

**Comment by LexiLikesFunkin** [comment]
I felt it was worth coming back to this after having a break from coding (sorry for being gone so long)
I still can't get it working, though I now have the .gradle folder. I'm still getting the same error because the directory i need isn't there.
![image](https://github.com/user-attachments/assets/8440f680-4959-4990-b60c-8869bbf79ec6)
![image](https://github.com/user-attachments/assets/33d3a520-2580-4b77-841d-56918c5ca7dc)
I think it's worth noting i'm not even using a copy of funkin android anymore, i'm literally just using a blank copy of HelloWorld from the Haxeflixel website

Edit: I also couldn't get wrapper to install in the gradle directory, neither could I get it to install in the code directory

**Comment by ghost** [comment]
can you try `set GRADLE_USER_HOME="(repo path)\.gradle"` and run compile again?

**Comment by LexiLikesFunkin** [comment]
it didn't fix anything
it's even more broken now, i cant even run gradle
reverting the changes hasn't fixed anything oh god
![image](https://github.com/user-attachments/assets/a77b2603-fd69-4f8e-be25-a2d5502813e9)

**Comment by LexiLikesFunkin** [comment]
Enviroment Variable stuff - as the installation of gradle said to do
![image](https://github.com/user-attachments/assets/ca5a044f-d360-4c14-b823-a288af9eb700)
![image](https://github.com/user-attachments/assets/eccddf8f-3793-4b29-a001-5d15505914e5)

**Comment by KarimAkra** [comment]
from what i know
gradle should be installed by lime at the end of the compile process in the export folder
it's not supposed to have a environment variable or be in your device's root directory

maybe try deleting that gradle environment variable?

**Comment by KarimAkra** [comment]
> ![image](https://private-user-images.githubusercontent.com/154026059/347618726-e2ca5553-336e-430c-8280-8c048fb03ee7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NzMxNzAsIm5iZiI6MTcyNDc3Mjg3MCwicGF0aCI6Ii8xNTQwMjYwNTkvMzQ3NjE4NzI2LWUyY2E1NTUzLTMzNmUtNDMwYy04MjgwLThjMDQ4ZmIwM2VlNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyN1QxNTM0MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZTA1MTFiMWUwN2JmOTk1M2VkZjEyOTg2OTFhYTg5MDM1YWMxNzI4NDkxYjU5Y2JiZjEyZDYwNTUzOTljOWUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JgdTXYeyz6u37F59_dczI_Xw0MTA7nD7n9zFavv8y08)

also looking at your JDK path it's kinda weird 
windows somtimes fails to read/write to some directories with some symbols maybe try simplifying the path name?

**Comment by LexiLikesFunkin** [comment]
Okay, i modified the JDK path, removing the + in the name, and re-setup lime for android, compiling now to see
i'll delete the gradle variable after if it doesnt work

**Comment by LexiLikesFunkin** [comment]
i got the same error...

**Comment by ghost** [comment]
> Enviroment Variable stuff - as the installation of gradle said to do ![image](https://private-user-images.githubusercontent.com/154026059/361850574-ca5a044f-d360-4c14-b823-a288af9eb700.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3Nzc5MTcsIm5iZiI6MTcyNDc3NzYxNywicGF0aCI6Ii8xNTQwMjYwNTkvMzYxODUwNTc0LWNhNWEwNDRmLWQzNjAtNGMxNC1iODIzLWEyODhhZjllYjcwMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyN1QxNjUzMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNWRjYmM3OGIyMzA1ODYyOWI5Mjc4N2Y1ODYwNDc1NmVkYzE0YTAzMDA2NmQ4NTMzNmQ2ODc3OTgyMmExNTEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CF2guo55k2F_Ejn_2IS0tVU98L7cT8_9OpZPVDRM-yk) ![image](https://private-user-images.githubusercontent.com/154026059/361850744-eccddf8f-3793-4b29-a001-5d15505914e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3Nzc5MTcsIm5iZiI6MTcyNDc3NzYxNywicGF0aCI6Ii8xNTQwMjYwNTkvMzYxODUwNzQ0LWVjY2RkZjhmLTM3OTMtNGIyOS1hMDAxLTVkMTU1MDU5MTRlNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyN1QxNjUzMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MzlmODhjNDljODE0MTgwZjYyYjgxMjk4MTU5MzNhZWE4YTIyNzRhNGRiZmMwMDc4MmZiNzU2MmQ4ZTNlN2ZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RZbTQnaf4VcIw8ZKi6bI5usKSf3iDFFp3T83XBs5_Y8)

why you have separate gradle, delete that gradle fully on your pc

**Comment by LexiLikesFunkin** [comment]
the C:\Gradle one? Alright...
what next?

**Comment by LexiLikesFunkin** [comment]
This thread is getting really long
if at any time you'd be happy to continue this on Discord, my username is lexilikesfunkin - i just dont want this getting too convoluted
