### ISSUE TITLE
When The 0.5.0 Fnf Update On Mobile Port Released 

### ISSUE THREAD

**Issue by CarGamerYoutuber** [MAJigsaw77/Funkin#29]
### Issue Checklist

- [X] I have properly named the enhancement
- [X] I have checked the issues/discussions pages to see if the enhancement has been previously suggested

### What is your suggestion, and why should it be implemented?

When The 0.5.0 Fnf Update On Mobile Port Released

**Comment by ghost** [comment]
When the source code releases, we'll try porting it asap

**Comment by CarGamerYoutuber** [comment]
Fine Until 2025 And You Blocked Me On Discord And Banned Me

**Comment by CarGamerYoutuber** [comment]
So Score Mode Released
