### ISSUE TITLE
Crash Report: Bf erect remixes are unplayable 

### ISSUE THREAD

**Issue by Frix-source** [MAJigsaw77/Funkin#32]
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Newgrounds (Web)

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0 

### Context (Provide screenshots or videos of the crash happening)

Bf erect remixes are unplayable in the game 0.5.0 the game just crashes when I click on any of the songs 

### Steps to reproduce

You know 

### Crash logs (can be found in the logs folder where Funkin.exe is)

Uhh

**Comment by moondroidcoder** [comment]
I assume this is an issue from 0.5.0

**Comment by Frix-source** [comment]
> I assume this is an issue from 0.5.0

Yes it is

**Comment by KarimAkra** [comment]
It's likely your phone's issue

**Comment by Frix-source** [comment]
> It's likely your phone's issue

Only coco erect does not work work

**Comment by Frix-source** [comment]
> It's likely your phone's issue

Mind fixing it when 0.5.1 comes out?

**Comment by KarimAkra** [comment]
> > It's likely your phone's issue
> 
> Mind fixing it when 0.5.1 comes out? 

We haven't even made the 0.5.0 release yet
You shouldn't be using these builds and should be well aware that there are bugs because we haven't released it yet.

**Comment by Frix-source** [comment]
> > > It's likely your phone's issue
> > 
> > 
> > Mind fixing it when 0.5.1 comes out?
> 
> We haven't even made the 0.5.0 release yet You shouldn't be using these builds and should be well aware that there are bugs because we haven't released it yet.

Ok thanks for the reply, I will wait for your 0.5.0 release

**Comment by sector-a** [comment]
I will playtest every single song later, so we will be sure everything is fine.

**Comment by Frix-source** [comment]
> I will playtest every single song later, so we will be sure everything is fine.

Thanks BTW when will you guys release 0.5.0?
