### ISSUE TITLE
Crash after character select light o cutscene

### ISSUE THREAD

**Issue by Gustsonic1682** [MAJigsaw77/Funkin#35]
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Newgrounds (Web)

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0 (New build)

### Steps to reproduce

Go to character select after The cutscene of the lights getting on The game crash

### Crash logs (can be found in the logs folder where Funkin.exe is)

Dont have The game only close

**Comment by FlapiIsADuck** [comment]
Hey how did you get the version 0.5.0 android apk?

**Comment by Gustsonic1682** [comment]
Go to actions

**Comment by Gustsonic1682** [comment]
After press build game for Android

**Comment by Gustsonic1682** [comment]
And press Android build

**Comment by Gustsonic1682** [comment]
You need tô wait for The developers tô compile The game

**Comment by Gustsonic1682** [comment]
Sorry for bad english

**Comment by FlapiIsADuck** [comment]
Tysm ive been searching for this for a month

**Comment by ghost** [comment]
do NOT share any apk/ipa's about these builds, thank you

**Comment by Gustsonic1682** [comment]
And The builds contains bugs

**Comment by Gustsonic1682** [comment]
The bugs IS already solved.

**Comment by FlapiIsADuck** [comment]
Idc i love with bugs

**Comment by FlapiIsADuck** [comment]
Idc I live with bugs

**Comment by FlapiIsADuck** [comment]
Is the new build faster and is it gonna come out when its done?
