### ISSUE TITLE
Add the old menu

### ISSUE THREAD

**Issue by FlapiIsADuck** [MAJigsaw77/Funkin#38]
### Issue Checklist

- [X] I have properly named my issue
- [ ] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Unofficial - Android

### Browser

None

### Version

0.5.0

### Description (include any images, videos, errors, or crash logs)

I always get the menu popup after i press right and acedentaly press c fix it

### Steps to Reproduce

C

**Comment by KarimAkra** [comment]
We've stopped development on this repository.
We won't be taking or fixing any bugs
