### ISSUE TITLE
Bug Report: [ android version crashes when opening]

### ISSUE THREAD

**Issue by hazzyYT** [MAJigsaw77/Funkin#4]

**Comment by moondroidcoder** [comment]
Provide a detailed explanation

**Comment by hazzyYT** [comment]
“Playtest.apk” when I downloaded it and opened the app it instantly closes saying “Friday Night Funkin’ has stopped” and then you told me download the other apk which is a 64 bit version and my device is 32 bit however the same issue is still happening. I downloaded it then I opened it and then it says the same thing “Friday Night Funkin’ has stopped”

**Comment by ghost** [comment]
JNI issue or 32-bits issue needs to be fixed

**Comment by hazzyYT** [comment]
How long will it take ?

**Comment by hazzyYT** [comment]
And also for the web version, for iOS devices, the website crashed when opening a song

**Comment by hazzyYT** [comment]
Here is a detailed explanation for ZACKDROID and the other guy:
For my Android Device which is a 32 bit Samsung Galaxy Tab S2
So when you first released the video, I downloaded the play test apk. However there was a problem, when I tap the app to open it, it instantly crashes saying “Friday Night Funkin has stopped”. So the problem is when I open it, the app crashes instantly. I figure this is an optimization problem maybe and told u on the GitHub. Then you responded saying “if the other apk doesn’t work download the other one” to which I did however now I am downloading the other apk which is “arm64” which is for 64 bit devices but nothing changed and the same error still occurs. My second option is I figured you had got both apks for 64 bit devices mixed up? And the “play test apk” is meant to be 32 bit devices.

So I figured I have an iPhone however I cannot jailbreak! So I decided to use the web version

For my IPhone 14 Pro:
So when I open the browser everything loads fine EXCEPT when I enter a song, the website crashes, allowing it to reload again. So I went back on and go to the song again and the same thing happens. The website crashes. And it says “a repeated errror has occurred” I asked others about this and they experience the same issue On IPHONE devices. HOWEVER, the songs such as “roses, senpai and thorns” CAN load but the others can’t. I figured this is ALSO an optimization problem however I am using a quite high performance phone but I am not a developer of a website, nor a coder. 
This error only occurs on iPhone devices

Here are two very clearly explained issues. One of which are of different devices. The issue on my android is happening to me however the issue on my iOS device is a universal issue to which I have tested on multiple iOS devices and asked a friend to test and the repeated error occurs. (See above if you forgot the error)

**Comment by ghost** [comment]
for iOS web due iOS limitations (fuck apple) we having this issue and we're not optimizers or not gonna optimize it so nothing we can do about it
for android we trying to fix for 32-bit's

**Comment by hazzyYT** [comment]
Ok thank you

**Comment by hazzyYT** [comment]
I tested the ipa and it works perfectly! Just that obviously after loading weekend 1 in story mode after the cutscene, there is an audio glitch which removes the audio but other than that it is really good I had a lot of fun playing it! Manage to fc milf aswell lol

**Comment by ghost** [comment]
32-bit issue has been fixed and will be include in next patch(?) but instant crash (on general) needed to fix still

**Comment by ghost** [comment]
both issues fixed and will include on next patch.
