### ISSUE TITLE
Bug Report: [Cant Open The Apk]

### ISSUE THREAD

**Issue by 5tupidBoy** [MAJigsaw77/Funkin#5]
![Screenshot_20240520-050217](https://github.com/FunkinDroidTeam/Funkin/assets/170229338/c9ecc673-9e0f-4435-a577-2e5080a0739c)

**Comment by moondroidcoder** [comment]
There are two apks, if one doesnt work, download the other one!

**Comment by 5tupidBoy** [comment]
Im 32bit phone,when im download the other,can't installed

**Comment by ghost** [comment]
our 32-bit builds are untested so that's normal we see that (dev note: I needed rebuild lime again)

**Comment by Gustsonic1682** [comment]
So when you gonna rebuild lime?

**Comment by ghost** [comment]
fixed will be include in new patch(?)
