### ISSUE TITLE
SDL ERROR

### ISSUE THREAD

**Issue by Gustsonic1682** [MAJigsaw77/Funkin#6]
Hey Zack, i've tried the two apks but doesn't work, my phone is Samsung Galaxy A015 and ITS 32 bits/armeabi-v7a , the message that appears is that in the archive in the lib/armeabi-v7a named liblime.so a symbol is missing, can you fix It please?

Thanks for you attention

**Comment by Gustsonic1682** [comment]
Sorry for bad english im Brazilian

**Comment by Gustsonic1682** [comment]
> Hey Zack, i've tried the two apks but doesn't work, my phone is Samsung Galaxy A015 and ITS 32 bits/armeabi-v7a , the message that appears is that in the archive in the lib/armeabi-v7a named liblime.so a symbol is missing can you fix It please?
> 
> Thanks for you attention

**Comment by DARKTORTA** [comment]
It's a general issue, i heard 32 bits in new update don't work

**Comment by ghost** [comment]
https://github.com/FunkinDroidTeam/Funkin/issues/5#issuecomment-2120290677

**Comment by ghost** [comment]
fixed will be include in new patch(?)
