### ISSUE TITLE
android/data/com.funkin.fnf can't be access by normal users (android 11 - android 14) + manual fix

### ISSUE THREAD

**Issue by oliver2999** [MAJigsaw77/Funkin#7]
**OS:** Android 13
**device:** realme C53
**model:** RMX3760
**problem:** 
/storage/emulated/0/Android/data/com.funkin.fnf and /storage/emulated/0/Android/obb/com.funkin.fnf  can't be access by normal users unless using third party application (MT manager) and third party permission (Shizuku) but i found even easier method using Inject Document Provider by modify the apk .
https://mt-manager.en.uptodown.com/android/download
create account on mt manager (you can use temporary email), login , select apk , press "function" , press "Inject Documents Provider" and press ok and the modified apk will be created
(just see the video and you will understand the rest)
![Screenshot_20240520-205853](https://github.com/FunkinDroidTeam/Funkin/assets/61278817/d3044323-685c-4089-9da5-57a8a5f6486a)

https://github.com/FunkinDroidTeam/Funkin/assets/61278817/8e39cba4-0519-4b4e-b2ae-b6909b47c797

**Comment by MAJigsaw77** [comment]
They can using zarchiver, I'm using android 13

**Comment by ghost** [comment]
incase if it's still not visible, use a pc or ZArchiver + Shizuku
